//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelDataRecorder.Database.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ID { get; set; }
        public string ErrorInnerException { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorInnerExceptionMessage { get; set; }
        public string StackTrace { get; set; }
        public Nullable<System.DateTime> ErrorTimeStamp { get; set; }
    }
}
