//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelDataRecorder.Database.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelDetail()
        {
            this.TravelDetailTrails = new HashSet<TravelDetailTrail>();
            this.TravelEmailExceptions = new HashSet<TravelEmailException>();
            this.TravelPlaceDetails = new HashSet<TravelPlaceDetail>();
        }
    
        public int Id { get; set; }
        public string Summary_ProjectName { get; set; }
        public string Summary_PrimeContractor { get; set; }
        public string Summary_ContractNumber { get; set; }
        public string Summary_TaskOrder { get; set; }
        public string Summary_CorName { get; set; }
        public Nullable<System.DateTime> Summary_SubmittedDate { get; set; }
        public string Summary_TravelerName { get; set; }
        public string Detail_AirportDepartingFrom { get; set; }
        public int Detail_TravelingFromCity { get; set; }
        public int Detail_TravelingFromState { get; set; }
        public int Detail_TravelingToCity { get; set; }
        public int Detail_TravelingToState { get; set; }
        public int Detail_ReturningToCity { get; set; }
        public int Detail_ReturningToState { get; set; }
        public Nullable<System.DateTime> Detail_DepartingDate { get; set; }
        public Nullable<System.DateTime> Detail_ReturningDate { get; set; }
        public Nullable<decimal> Detail_TotalDays { get; set; }
        public string Detail_TravelPurpose { get; set; }
        public string Detail_TravelSitePOC { get; set; }
        public Nullable<decimal> Cost_CostOfAirFare { get; set; }
        public Nullable<decimal> Cost_PerDiemRate { get; set; }
        public Nullable<decimal> Cost_TotalPerDiem { get; set; }
        public Nullable<decimal> Cost_RegistrationFee { get; set; }
        public Nullable<decimal> Cost_RentalCar { get; set; }
        public Nullable<decimal> Cost_Hotel { get; set; }
        public Nullable<decimal> Cost_Miscellaneous { get; set; }
        public Nullable<decimal> Cost_TotalExpense { get; set; }
        public string Cost_ODCBudgetStatus { get; set; }
        public int UserID { get; set; }
        public Nullable<int> LastStatus { get; set; }
        public Nullable<short> IsProcedural { get; set; }
    
        public virtual TravelUser TravelUser { get; set; }
        public virtual TravelStatusMaster TravelStatusMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelDetailTrail> TravelDetailTrails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelEmailException> TravelEmailExceptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelPlaceDetail> TravelPlaceDetails { get; set; }
        public virtual TravelCity TravelCity { get; set; }
        public virtual TravelCity TravelCity1 { get; set; }
        public virtual TravelState TravelState { get; set; }
        public virtual TravelState TravelState1 { get; set; }
    }
}
