//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelDataRecorder.Database.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelNotification
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
        public int UserId { get; set; }
        public bool Status { get; set; }
        public Nullable<int> StepNotificationId { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public Nullable<int> TravelId { get; set; }
        public Nullable<int> ProcessedBy { get; set; }
    
        public virtual TravelUser TravelUser { get; set; }
        public virtual TravelUser TravelUser1 { get; set; }
    }
}
