//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelDataRecorder.Database.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelDetailTrail
    {
        public int Id { get; set; }
        public int TravelId { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> ProcessedBy { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Comments { get; set; }
        public Nullable<int> StepNotes { get; set; }
        public Nullable<int> NextActionRole { get; set; }
    
        public virtual TravelStatusMaster TravelStatusMaster { get; set; }
        public virtual TravelDetail TravelDetail { get; set; }
    }
}
