//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelDataRecorder.Database.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelCity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelCity()
        {
            this.TravelPlaceDetails = new HashSet<TravelPlaceDetail>();
            this.TravelDetails = new HashSet<TravelDetail>();
            this.TravelDetails1 = new HashSet<TravelDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int StateId { get; set; }
    
        public virtual TravelState TravelState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelPlaceDetail> TravelPlaceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelDetail> TravelDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelDetail> TravelDetails1 { get; set; }
    }
}
