//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelDataRecorder.Database.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelEmailException
    {
        public int Id { get; set; }
        public string EmailTo { get; set; }
        public string EmailFrom { get; set; }
        public int TravelId { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<short> status { get; set; }
    
        public virtual TravelDetail TravelDetail { get; set; }
    }
}
